apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-platform
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - manifests/auth-service.yaml
  - manifests/patient-service.yaml
  - manifests/doctor-service.yaml
  - manifests/availability-service.yaml
  - manifests/appointment-service.yaml
  - manifests/medical-records-service.yaml
  - manifests/realtime-service.yaml
  - manifests/notification-service.yaml
  - manifests/audit-service.yaml
  - manifests/kong-gateway.yaml
