FROM node:22-alpine

WORKDIR /app

ARG SERVICE_NAME
ENV SERVICE_NAME=${SERVICE_NAME}

COPY package.json tsconfig.base.json .env.example ./
COPY infra ./infra
COPY packages ./packages
COPY services ./services

RUN npm install --workspaces --include-workspace-root

EXPOSE 3000
CMD ["sh", "-c", "npm run start --workspace services/${SERVICE_NAME}"]
